# Generated by Django 2.2.4 on 2020-06-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dept', models.CharField(blank=True, max_length=70, null=True)),
                ('group', models.CharField(blank=True, max_length=30, null=True)),
                ('gpa', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'group', '-updated_at'],
            },
        ),
    ]
