# Generated by Django 2.2.4 on 2020-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mySkill', models.CharField(blank=True, max_length=69, null=True)),
                ('iKnow', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['iKnow', '-updated_at'],
            },
        ),
    ]
